trigger:
- main

pool:
  name: 'Default'
  demands:
    - Agent.OS -equals Windows_NT

steps:
- powershell: Write-Host "Hello, world from Windows self-hosted agent!"
  displayName: 'Run a one-line PowerShell script'

- powershell: |
    Write-Host "Running on Windows self-hosted agent"
    Write-Host "Add build, test, and deployment steps here"
    Write-Host "Reference: https://aka.ms/yaml"
  displayName: 'Run a multi-line PowerShell script'